#!/bin/bash

bold () { printf "\e[1m" ; $@ ; printf "\e[0m"; }
selected () { printf "\e[4m" ; $@ ; printf "\e[0m"; }
upper () { printf '%s\n' "$@" | tr '[:lower:]' '[:upper:]'; }

header1 () { printf "\e[32m\e[1m\e[4m" ; $@ | tr '[:lower:]' '[:upper:]'; printf "\e[0m"; }
header2 () { printf "\e[92m" ; $@ ; printf "\e[0m"; }


echo ''
header1 echo "=============== $1 ==============="